apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_station_2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather_station_2
  template:
    metadata:
      labels:
        app: weather_station_2
    spec:
      containers:
        - name: weather_station_2_image
          image: mostafaeltawy/weatherstationimage:latest
        - env:
            -name:stationid
            -value:"2"
          ports:
            - containerPort: 8082