apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherstation1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherstation1
  template:
    metadata:
      labels:
        app: weatherstation1
    spec:
      containers:
        - name: weatherstation1image
          image: mostafaeltawy/weather:latest
          env:
          - name: station_id
            value: "1"
          ports:
            - containerPort: 8081