apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_station_7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather_station_7
  template:
    metadata:
      labels:
        app: weather_station_7
    spec:
      containers:
        - name: weather_station_7_image
          image: mostafaeltawy/weatherstationimage:latest
        - env:
            -name:station_id
            -value:"7"
          ports:
            - containerPort: 8087