apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_station_4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather_station_4
  template:
    metadata:
      labels:
        app: weather_station_4
    spec:
      containers:
        - name: weather_station_4_image
          image: mostafaeltawy/weatherstationimage:latest
        - env:
            -name:stationid
            -value:"4"
          ports:
            - containerPort: 8084