apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_station_3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather_station_3
  template:
    metadata:
      labels:
        app: weather_station_3
    spec:
      containers:
        - name: weather_station_3_image
          image: mostafaeltawy/weatherstationimage:latest
        - env:
        - name: stationid
          value: "3"
          ports:
            - containerPort: 8083