apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaprocessorsimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaprocessorsimage
  template:
    metadata:
      labels:
        app: kafkaprocessorsimage
    spec:
      containers:
        - name: kafkaprocessorsimage
          image: mostafaeltawy/kafkaprocessorsimage:latest

          ports:
            - containerPort: 8082