apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaprocessorimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaprocessorimage
  template:
    metadata:
      labels:
        app: kafkaprocessorimage
    spec:
      containers:
        - name: kafkaprocessorimage
          image: kotb00/kafkaprocessorimage:latest

          ports:
            - containerPort: 8052
